// <auto-generated />
using GraphQL.NetCore.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQL.NetCore.Api.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    [Migration("20210710224147_seed-data")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("GraphQL.NetCore.Api.Model.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Eric",
                            LastName = "Evans"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Robert",
                            LastName = "Martin"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Martin",
                            LastName = "Fowler"
                        });
                });

            modelBuilder.Entity("GraphQL.NetCore.Api.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Title = "Domain-driven design"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Title = "Clean Architecture"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Title = "Refactoring"
                        });
                });

            modelBuilder.Entity("GraphQL.NetCore.Api.Model.Book", b =>
                {
                    b.HasOne("GraphQL.NetCore.Api.Model.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("GraphQL.NetCore.Api.Model.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
